### ISSUE TITLE
Remover refreshToken

### ISSUE THREAD

**Issue by jucastilhoduarte** [ipsBruno/haval-h6-gwm-alexa-chatgpt-mqtt-integration#1]
Amigo você comittou seu accessToken e refreshToken nesse repositório. Não seria melhor remover? Colocar no .gitignore

**Comment by ipsBruno** [comment]
Grande Juliano, tudo bom?

Sim notei, mas já expirou o access_token

Obrigado, colocarei em .gitignore.

Se tiver algum pull request ai manda pra gente melhorar o código, fiz bem nas pressas
