### ISSUE TITLE
Postman, Python e Home Assistant

### ISSUE THREAD

**Issue by carvalr** [ipsBruno/haval-h6-gwm-alexa-chatgpt-mqtt-integration#4]
Bruno, primeiro meus parabéns por possibilitar esse projeto.
Temos que ter o primeiro passo para conseguirmos coisas maiores e você está desbravando esse terreno. Se alguém já o tinha feito, ainda não havia compartilhado e guardou na gaveta. Logo, você foi o primeiro.

Vou trabalhar nos tempos livres para fazer uma integração com o Home Assistant e exibir as informações do carro e da saúde da bateria, através de um leitor OBDII + Car Scanner, que já tem o perfil do carro.

Eu estive brincando com o seu código nesse feriado e o converti para Python, mas não consegui fazer a chamada com os certificados e o programa em C# que disponibilizou.
Consegui conectar na API via Postman após gerar os arquivos .pem e .pfx alterando o source C#. Agora, é fazer funcionar no Python, o que ainda não tive tempo. Mas conectando via Postman já é um grande avanço.
Se eu tiver sucesso, vou criar um fork do seu projeto.

![image](https://github.com/ipsBruno/haval-h6-gwm-alexa-chatgpt-mqtt-integration/assets/74059823/66e66754-db89-40e6-ab3f-e5a93cac15dd)

P.S.: Temos um grupo no WhatsApp, o "Havaleiros Brasil", com mais de 1400 pessoas. Se quiser participar, sempre sai coisa boa lá.

**Comment by ipsBruno** [comment]
Muito bom amigo.

Se pegar a requisição em CURL dá pra refazer ela todinha empython sim
Inclusive python é melhor que nodejs para trabalhar com estes certificados..

Já pedi pra entrar no grupo havaleiros

Grande abraço

**Comment by carvalr** [comment]
@ipsBruno, se já entrou, me chama lá para falarmos.

**Comment by JRFabbi** [comment]
Fala pessoal, boa tarde!
Trabalhei no projeto de integração do SmartThings do HA e recentemente adquiri um H6 GT, antes tinha um VOLVO com tudo integrado no HA e quero ajudar no projeto pra integrar o Haval no HA para continuar com meu painel funcionando
Vou pegar meu carro entre sexta e segunda, em quanto isto vou estudar até onde vocês já chegaram

**Comment by carvalr** [comment]
Só usar, então: https://github.com/havaleiros/hassio-haval-h6-to-mqtt.
